# Generated by Django 5.2.7 on 2025-11-13 18:05

from django.db import migrations


def create_default_task_statuses(apps, schema_editor):
    TaskStatus = apps.get_model('companies', 'TaskStatus')
    
    # Criar status padrão de tarefas
    default_statuses = [
        {'name': 'Pendente', 'codename': 'pending'},
        {'name': 'Em Progresso', 'codename': 'in_progress'},
        {'name': 'Concluída', 'codename': 'completed'},
        {'name': 'Cancelada', 'codename': 'cancelled'},
    ]
    
    for status_data in default_statuses:
        TaskStatus.objects.get_or_create(
            codename=status_data['codename'],
            defaults={'name': status_data['name']}
        )


def remove_default_task_statuses(apps, schema_editor):
    TaskStatus = apps.get_model('companies', 'TaskStatus')
    TaskStatus.objects.filter(
        codename__in=['pending', 'in_progress', 'completed', 'cancelled']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_taskstatus_task'),
    ]

    operations = [
        migrations.RunPython(create_default_task_statuses, remove_default_task_statuses),
    ]
